version: '3.3'

services:
  db:
    image: postgres
    container_name: anymind_db
    logging:
      driver: none
    ports:
      - '54321:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

  anymind_service:
    depends_on:
      - db
    container_name: anymind_service
    build:
      context: .
      dockerfile: ./Dockerfile
    expose:
      - 8811
    ports:
      - '8811:8811'
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # Launching Fee Service
      echo -e 'Waiting for Postgres to start...'
      sh /app/wait-for.sh db:5432 -- /app/anymind --port 8811
      "